---
- name: Setup new server
  hosts: webservers
  remote_user: root

  vars:
 	  password: password

 tasks:

 - name: Upgrade All Packages
 	  yum: name=* state=latest update_cahce=yes

 - name: Install Packages
 	  yum: >
 	  	state=latest
 	  	name={{ item }}
 	  	with_items:
 	  		- vim
 	  		- git
 	  		- tcpdump

- name: Create default user blah
 	  user: >
 	  	name=blah
 	  	password={{password}}
 	  	group=wheel

- name: Copy SSH keys over
    Copy: >
      src=~/.ssh/dev
      dest=/home/blah/.ssh/dev
   		owner=blah
   		group=blah
   		mode=0600
