---
- name: Setup SSH, SSH keys, users, and install packages
  hosts: all
  remote_user: root
  
  vars:
	password: password
  

  tasks:
	- name: Install programs
	yum: name=vim state=latest update_cache=yes

        - name: Setup Users and passwords
	  user: >
		name=username
		shell=/bin/zsh
		group=wheel
		append=yes
		password={{password}}

        - name: Copy over sshd_config file

        - name: Copy over ssh keys

      
